sfmc_personalization.settings:
  type: config_object
  label: 'SFMC Personalization Settings'
  mapping:
    beacon_script_url:
      type: string
      label: 'JavaScript Integration Beacon Script URL'
    async:
      type: boolean
      label: 'Async'
    script_location:
      type: string
      label: 'Script Location'
      constraints:
        Choice: ['header', 'footer']
    allowed_domains:
      type: string
      label: 'Allowed Domains'
      sequence:
        type: string
    content_zones:
      type: sequence
      label: 'Global Content Zones'
      sequence:
        label: 'Content Zone'
        mapping:
          label:
            type: string
            label: 'Content Zone label'
          selector:
            type: string
            label: 'Content Zone CSS selector'
    user_fields:
      type: sequence
      label: 'User Fields'
      sequence:
        type: string

sfmc_personalization.pages:
  type: config_object
  label: 'SFMC Personalization Pages Settings'
  mapping:
    pages:
      type: sequence
      label: 'Personalization pages'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Page name'
          condition_type:
            type: string
            label: 'Condition type'
          condition_value:
            type: string
            label: 'Condition value'
          content_zones:
            type: sequence
            label: 'Content zones'
            sequence:
              type: mapping
              mapping:
                label:
                  type: string
                  label: 'Content zone label'
                selector:
                  type: string
                  label: 'CSS selector'
