sfmc_personalization.settings:
  type: config_object
  label: 'SFMC Personalization Settings'
  mapping:
    beacon_script_url:
      type: string
      label: 'JavaScript Integration Beacon Script URL'
    async:
      type: boolean
      label: 'Async'
    script_location:
      type: string
      label: 'Script Location'
      constraints:
        Choice: ['header', 'footer']
    allowed_domains:
      type: string
      label: 'Allowed Domains'
      sequence:
        type: string
      validation_criteria: 'valid_domain'
    content_zones:
      type: sequence
      label: 'Global Content Zones'
      sequence:
        label: 'Content Zone'
        mapping:
          label:
            type: string
            label: 'Content Zone label'
          selector:
            type: string
            label: 'Content Zone CSS selector'
    user_fields:
      type: sequence
      label: 'User Fields'
      sequence:
        type: string
      description: 'Map Drupal user fields to SFMC attributes'

sfmc_personalization.pages:
  type: config_object
  label: 'SFMC Personalization Pages Settings'
  mapping:
    default_page:
      type: integer
      label: 'Default page type index'
    pages:
      type: sequence
      label: 'Personalization pages'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Page name'
          path_type:
            type: string
            label: 'Path type'
          path:
            type: string
            label: 'Path pattern'
          content_zones:
            type: sequence
            label: 'Content zones'
            sequence:
              type: mapping
              mapping:
                label:
                  type: string
                  label: 'Content zone label'
                selector:
                  type: string
                  label: 'CSS selector'
